# Generated by Django 4.2 on 2024-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontactapplication',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='usercontactapplication',
            name='phone',
        ),
        migrations.AddField(
            model_name='usercontactapplication',
            name='message',
            field=models.TextField(default='tes'),
            preserve_default=False,
        ),
    ]
