# Generated by Django 4.2 on 2024-07-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_galleryphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.FileField(upload_to='photos/%Y/%m/'),
        ),
    ]
